# 1. Shape Manipulation

- arr.reshape()
- arr.ravel()
- arr.flatten()
- arr.resize()

In [11]:
import numpy as np 

# 1. arr.reshape()
a=[1,2,3,4,5,6]
arr=np.array(a)
#want new shape of array based on arr
#there are three types of order 'F': column major, 'C': Row major, 'A': row major
b=arr.reshape((2,3), order='F')
b

array([[1, 3, 5],
       [2, 4, 6]])

In [12]:
# 2. arr.ravel()
a=np.array([[1,2],[3,4]])
b=a.ravel(order='F')
b

array([1, 3, 2, 4])

In [13]:
# arr.flatten() used to flatten multidimensional array into vector
a=np.array([[1,2],[3,4]])
b=a.flatten(order='F')
b

array([1, 3, 2, 4])

In [14]:
#arr.resize()
a=np.array([10,20,30])
a.resize((2,3,2))
a

array([[[10, 20],
        [30,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0]]])

# 2. Transpose and Axies Manipulation

- arr.transpose()
- np.swapaxes()
- np.moveaxis()

In [15]:
#arr.transpose() converts rows in column and column in row
a=np.array([[1,2], [3,4]])
b=a.transpose()
c=a.transpose(1,0)
d=a.transpose(0,1)

In [16]:
b

array([[1, 3],
       [2, 4]])

In [17]:
c

array([[1, 3],
       [2, 4]])

In [18]:
d

array([[1, 2],
       [3, 4]])

In [19]:
# 2 np.swapaxes()
a = np.array([[[1], [2]], [[3], [4]]]) #Shape:(2,2,1)
b = np.swapaxes(a, 0, 2) # New Shape: (1,2,2)

In [20]:
b

array([[[1, 3],
        [2, 4]]])

In [21]:
a

array([[[1],
        [2]],

       [[3],
        [4]]])

In [22]:
#np.moveaxis()
a=np.ones((2,3,4)) #Shape: (2,3,4)

In [23]:
b=np.moveaxis(a, 0, -1) #New Shape: (3,4,2)

In [24]:
# Create a 3D array: shape (2,3,4)
a=np.arange(24).reshape(2,3,4)

# Move axis 0 (first) to the last position
b=np.moveaxis(a,0,-1)

print("Original shape:", a.shape) # (2,3,4)
print("New shape:", b.shape)      # (3,4,2)

Original shape: (2, 3, 4)
New shape: (3, 4, 2)


# 3. Array Manipulation Joins

- concatenate()
- stack()
- hstack()
- vstack()

In [25]:
# concatenate()
# used to join array sequence on basis of axis
a = np.array([[1,2]]) # two dimension array
b = np.array([[3,4]]) # two dimension array
c = np.concatenate((a,b), axis = 0)

In [26]:
c.shape

(2, 2)

In [28]:
c = np.concatenate((a,b), axis = 1)

In [29]:
c.shape

(1, 4)

In [32]:
# stack ()
# joins array allow new dimension as well
a = np.array([1,2]) # two dimension array
b = np.array([3,4]) # two dimension array
c = np.stack((a,b), axis = 1)

In [33]:
c

array([[1, 3],
       [2, 4]])

In [34]:
# hstack()
a = np.array([1,2]) # two dimension array
b = np.array([3,4]) # two dimension array
c = np.hstack((a,b))

In [35]:
c

array([1, 2, 3, 4])

In [36]:
# vstack()
a = np.array([1,2]) # two dimension array
b = np.array([3,4]) # two dimension array
c = np.stack((a,b))

In [37]:
c

array([[1, 2],
       [3, 4]])