# NumPy array Broadcasting

broadcasting allows us to perform elements based operations.
also useful when we want operation in current array.
also useful when we work with different shape of arrays together for arithmetic operations.

# Scaler Broadcasting

In [2]:
import numpy as np 

a=np.array([1,2,3])
result = a + 10
print(result)

[11 12 13]


# 1D to 2D broadcasting

In [3]:
a=np.array([[1],[2],[3]])
b=np.array([10,20,30])
result = a * b
print(result)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


# Row wise Broadcasting

In [4]:
base_load = np.array([[60],[70],[80]]) #shape(3,1)
daily_factors = np.array([0.9,1.0,1.1,1.2]) #shape(4,)

adjusted = base_load * daily_factors #shape(3,4)

In [5]:
adjusted

array([[54., 60., 66., 72.],
       [63., 70., 77., 84.],
       [72., 80., 88., 96.]])

# Broadcasting using np.newaxis

In [6]:
a=np.array([1,2,3]) # shape(3,)
b=a[:, np.newaxis] # shape(3,1)
c=np.array([10,20]) #shape(2,)
result=b*c #shape(3,2)

In [7]:
result

array([[10, 20],
       [20, 40],
       [30, 60]])

In [10]:
result = a*c #will generate error because level issue

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

# Column wise broadcasting using axis

In [11]:
hourly_profile  = np.linspace(0.8,1.2,24) #shape(24,)
load = np.array([100,120,90]) #shape(3,)
hourly_matrix = load[: , np.newaxis] * hourly_profile #shape(3,24)

In [12]:
hourly_matrix

array([[ 80.        ,  81.73913043,  83.47826087,  85.2173913 ,
         86.95652174,  88.69565217,  90.43478261,  92.17391304,
         93.91304348,  95.65217391,  97.39130435,  99.13043478,
        100.86956522, 102.60869565, 104.34782609, 106.08695652,
        107.82608696, 109.56521739, 111.30434783, 113.04347826,
        114.7826087 , 116.52173913, 118.26086957, 120.        ],
       [ 96.        ,  98.08695652, 100.17391304, 102.26086957,
        104.34782609, 106.43478261, 108.52173913, 110.60869565,
        112.69565217, 114.7826087 , 116.86956522, 118.95652174,
        121.04347826, 123.13043478, 125.2173913 , 127.30434783,
        129.39130435, 131.47826087, 133.56521739, 135.65217391,
        137.73913043, 139.82608696, 141.91304348, 144.        ],
       [ 72.        ,  73.56521739,  75.13043478,  76.69565217,
         78.26086957,  79.82608696,  81.39130435,  82.95652174,
         84.52173913,  86.08695652,  87.65217391,  89.2173913 ,
         90.7826087 ,  92.34782609,  9

# Conditional Broadcasting

In [13]:
voltages = np.array([1.01,0.98,1.05,0.92])
status = np.where(voltages<0.95, "LOW", "OK")

In [14]:
status

array(['OK', 'OK', 'OK', 'LOW'], dtype='<U3')

# Challenge 1:

In [52]:
base_load = np.array([20,40,60,80])
days_factor = np.array([1,2,3,4,5,6,7])

weekly_load_matrix = base_load[:, np.newaxis] * days_factor
print(weekly_load_matrix)

[[ 20  40  60  80 100 120 140]
 [ 40  80 120 160 200 240 280]
 [ 60 120 180 240 300 360 420]
 [ 80 160 240 320 400 480 560]]


# Challenge 2:

In [56]:
hourly_profile = np.array([2,4,6,8,10,12])
weekly_load_over_time = weekly_load_matrix[:,:, np.newaxis] + hourly_profile 

In [57]:
weekly_load_over_time

array([[[ 22,  24,  26,  28,  30,  32],
        [ 42,  44,  46,  48,  50,  52],
        [ 62,  64,  66,  68,  70,  72],
        [ 82,  84,  86,  88,  90,  92],
        [102, 104, 106, 108, 110, 112],
        [122, 124, 126, 128, 130, 132],
        [142, 144, 146, 148, 150, 152]],

       [[ 42,  44,  46,  48,  50,  52],
        [ 82,  84,  86,  88,  90,  92],
        [122, 124, 126, 128, 130, 132],
        [162, 164, 166, 168, 170, 172],
        [202, 204, 206, 208, 210, 212],
        [242, 244, 246, 248, 250, 252],
        [282, 284, 286, 288, 290, 292]],

       [[ 62,  64,  66,  68,  70,  72],
        [122, 124, 126, 128, 130, 132],
        [182, 184, 186, 188, 190, 192],
        [242, 244, 246, 248, 250, 252],
        [302, 304, 306, 308, 310, 312],
        [362, 364, 366, 368, 370, 372],
        [422, 424, 426, 428, 430, 432]],

       [[ 82,  84,  86,  88,  90,  92],
        [162, 164, 166, 168, 170, 172],
        [242, 244, 246, 248, 250, 252],
        [322, 324, 326, 328, 330, 

In [58]:
weekly_load_over_time.shape

(4, 7, 6)