# Numpy

it is numeric python array.
array are fixed in a size and not dynamic like linked list.
arrays are homogenous.
it is useful for scientific computing in python.
it provides us maths,science,slicing,grouping,merging,indexing functionality it can be 1D,2D,ND.

In [1]:
#import numpy for learning purpose
import numpy as np #np is alias to our numpy module

# 1. create numpy using python sequences

In [3]:
#syntax
# a=np.array(obj) # here obj can be list,tuple or 2d list
l1=[10,20,30]
a=np.array(l1)
t=(11,22,33,44)
b=np.array(t)
l2=[[1,2],[5,6],[0,1]]
c=np.array(l2)

In [4]:
a

array([10, 20, 30])

In [5]:
b

array([11, 22, 33, 44])

In [6]:
c

array([[1, 2],
       [5, 6],
       [0, 1]])

# 2. Create numpy array using initialization function

In [7]:
#used to create an array with default value 0
# syntax np.zeros((dimension in tuple))
x=np.zeros((5)) #this will create single dimension
y=np.zeros((3,5)) # 2 dimension
z=np.zeros((3,2,5)) # 3 dimension

In [8]:
x

array([0., 0., 0., 0., 0.])

In [9]:
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
#used to create an array with default value 1
x=np.ones((2,3))

In [12]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#create an array with constant values or specific values
const_array=np.full((5,3),10)

In [14]:
const_array

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [15]:
#creating an identity matrix
a_identity=np.eye(3)

In [16]:
a_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
unit=np.empty((2,2))

In [18]:
unit

array([[6.95199682e-310, 1.48539705e-313],
       [1.33685735e-311, 6.23042070e-307]])

# 3. Create numpy array using ranges and intervals


In [ ]:
# arange
# linspace
# logspace

In [19]:
#arange work like range function in python
x=np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [20]:
# 5 values between 0 and 1 inclusive 0 and 1
y=np.linspace(0,1,5)

In [21]:
y

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# 4 values from 10^1 to 10^5
c=np.logspace(1,3,4)
c

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

# 4. Create numpy array using random generator
    np.random.rand() #uniform distribution
    np.random.randn() #n distribution
    np.random.randint() #int uniform distribution

In [23]:
uniform_a = np.random.rand(3,4)
uniform_a

array([[0.4615747 , 0.05758319, 0.11841276, 0.08136974],
       [0.6580936 , 0.44850295, 0.25840664, 0.08626078],
       [0.48389429, 0.22375944, 0.38755728, 0.18028298]])

In [24]:
int_array = np.random.randint(10,50,size=(3,3))
int_array

array([[37, 23, 30],
       [12, 22, 11],
       [10, 27, 38]])

In [25]:
#normal distribution array
normal_a=np.random.randn(5)
normal_a

array([-0.60424218, -1.01348819, -0.53075486,  0.33733461,  1.56070948])

# NumPy Attributes

In [30]:
#shape used to get idea on array dimension and shape
normal_a.shape

(5,)

In [31]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [33]:
#ndim will share array is 2,1,3,4,5 dimension of array
print(a.ndim)

2


In [34]:
#datatype of array
a.dtype

dtype('int32')

In [35]:
#size of array
a.size

6

In [36]:
#itemsize return byte of each element
a.itemsize

4

In [37]:
#nbytes returns total bytes occupies by array
a.nbytes

24

In [39]:
#transpose of the array
print("Original array:\n", a)
print("Transpose array:\n",a.T)

Original array:
 [[1 2 3]
 [4 5 6]]
Transpose array:
 [[1 4]
 [2 5]
 [3 6]]


In [40]:
# data gives the pointer of memory where array is stored
print(a.data)

In [42]:
#Exercise 1
new_list=[1.01,0.98,1.00,1.02,0.99]
new_array=np.array(new_list)

print(new_array.itemsize)
print(new_array.size)
print(new_array.dtype)

8
5
float64


In [43]:
#Exercise 2
new_array = np.full((5,),50)
new_array

array([50, 50, 50, 50, 50])

# NumPy Arithmetic Functions
    np.add()
    np.subtract()
    np.multiply()
    np.divide()
    np.power()
    np.mod()

In [44]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[1,1,1],[2,2,2]])

In [45]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
b

array([[1, 1, 1],
       [2, 2, 2]])

In [47]:
a.dtype

dtype('int32')

In [48]:
c=np.add(a,b)

In [49]:
c

array([[2, 3, 4],
       [4, 5, 6]])

In [50]:
c=np.subtract(a,b)
c

array([[0, 1, 2],
       [0, 1, 2]])

In [52]:
c=np.multiply(a,b)
c

array([[1, 2, 3],
       [4, 6, 8]])

In [53]:
c=np.divide(a,b)
c

array([[1. , 2. , 3. ],
       [1. , 1.5, 2. ]])

In [54]:
c=np.power(a,2)

In [55]:
c

array([[ 1,  4,  9],
       [ 4,  9, 16]], dtype=int32)

In [56]:
c=np.mod(a,b)
c

array([[0, 0, 0],
       [0, 1, 0]])

# Statistical Functions
    np.mean()
    np.median()
    np.std()
    np.var()
    np.min()
    np.max()

In [57]:
a=[10,20,30,14,25]
arr=np.array(a)
arr

array([10, 20, 30, 14, 25])

In [58]:
np.mean(arr)

19.8

In [59]:
np.median(arr)

20.0

In [60]:
np.std(arr)

7.222188034107115

In [61]:
np.var(arr)

52.160000000000004

In [62]:
np.min(arr)

10

In [63]:
np.max(arr)

30

# Trignometric Functions
    np.sin() #sine
    np.cos() #cosine
    np.tan() #tangent
    np.degrees() #radians to degree
    np.radians() #degree to radians
    np.arcsin() #inverse sine

In [64]:
arr

array([10, 20, 30, 14, 25])

In [65]:
np.sin(np.pi/2)

1.0

# Exponential and Logarithmic functions
    np.exp() #Exponential
    np.log() #Natural log
    np.log10() #Base 10 log
    np.log2() #Base 2 log

In [66]:
arr

array([10, 20, 30, 14, 25])

In [67]:
np.exp(arr)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 1.20260428e+06,
       7.20048993e+10])

In [68]:
np.log(arr)

array([2.30258509, 2.99573227, 3.40119738, 2.63905733, 3.21887582])

In [69]:
np.log10(arr)

array([1.        , 1.30103   , 1.47712125, 1.14612804, 1.39794001])

In [70]:
np.log2(arr)

array([3.32192809, 4.32192809, 4.9068906 , 3.80735492, 4.64385619])

# Rounding and Truncating Integer functions
    np.round()
    np.floor()
    np.ceil()
    np.trunc()

In [71]:
arr1=[1.25,2.36,4.05,2.0,1.16]
new = np.array(arr1)
new

array([1.25, 2.36, 4.05, 2.  , 1.16])

In [72]:
np.round(new)

array([1., 2., 4., 2., 1.])

In [73]:
np.floor(new)

array([1., 2., 4., 2., 1.])

In [74]:
np.ceil(new)

array([2., 3., 5., 2., 2.])

In [76]:
np.trunc(new)

array([1., 2., 4., 2., 1.])