# Numpy Indexes

In [2]:
import numpy as np 

arr = np.array([10,20,30,40]) #single dimension array
print(arr[0]) #10
print(arr[-1]) #40(last element)

10
40


In [3]:
grid = np.array([[1,2,3],[4,5,6]])
print(grid[1][2]) #6

6


In [4]:
grid[-1][-1]

6

In [5]:
print(grid[-1][-2]) #5
print(grid[-1][-3]) #4
print(grid[-2][-1]) #3
print(grid[-2][-2]) #2
print(grid[-2][-3]) #1
print(grid[0][0]) #1
print(grid[0][1]) #2
print(grid[0][2]) #3
print(grid[1][0]) #4
print(grid[1][1]) #5
print(grid[1][2]) #6

5
4
3
2
1
1
2
3
4
5
6


# Array Indexing and slicing

In [6]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4]) #[20,30,40]
print(arr[:3]) #[10,20,30]
print(arr[::2]) #Every second element [10,30,50]
print(arr[-3:]) #[40,50,60]

[20 30 40]
[10 20 30]
[10 30 50]
[40 50 60]


In [7]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix[0:2, 1:]) #Rows 0-1, columns 1-end
print(matrix[:,0]) #All rows , column 0
print(matrix[1]) #Row 1
print(matrix[::-1, ::-1])

[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [9]:
#create a 3d array with shape(2 blocks,3 rows, 4 columns)
cube = np.arange(2*3*4).reshape(2,3,4)
print(cube)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
print(cube[0, :, 1:3])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [13]:
import numpy as np
#shape: (2 days, 3 substations, 4 time blocks)
voltages = np.array([
    [[1.00, 1.01, 0.99, 0.98],
     [1.02, 1.01, 0.97, 0.96],
     [0.99, 1.00, 1.01, 0.98]],

    [[1.03, 1.01, 0.95, 0.97],
     [1.00, 1.02, 0.96, 0.94],
     [0.98, 0.99, 1.00, 0.97]]
])

In [24]:
# 1 Voltage at Day 1, substation 2 and timeblock 3
voltages[0,1,2]

0.97

In [25]:
# 2 Extract all time block from day 2 and substation 1
voltages[1,0,:]

array([1.03, 1.01, 0.95, 0.97])

In [26]:
# 3 Extract time block 2 for all substation on both days
voltages[:,:,1]

array([[1.01, 1.01, 1.  ],
       [1.01, 1.02, 0.99]])

In [27]:
# 4 all substation and timeblock on day 1/
voltages[0,:,:]

array([[1.  , 1.01, 0.99, 0.98],
       [1.02, 1.01, 0.97, 0.96],
       [0.99, 1.  , 1.01, 0.98]])

# Indexing and slicing functions

- np.take() #Extract elements from array on based of indexes
- np.compress() #filter using boolean
- np.where() #conditional indexing
- np.extract() #extract elements if condition is true
- np.nonzero() #indices of non zero elements
- np.flatnonzero() #flatten indices of non zero elements
- np.argwhere() #indices and elements if condition is true

In [28]:
#np.take()
arr = np.array([10,20,30,40,50])
indices = [0,2,4]

result = np.take(arr, indices)
print(result)

[10 30 50]


In [34]:
#np.compress() filter along an axis using a boolean mask
arr = np.array([[1,2], [3,4], [5,6]])
mask = [False, True, True]
result = np.compress(mask, arr, axis=0)
print(result)

[[3 4]
 [5 6]]


In [30]:
#np.where() conditional selection and replacement
arr = np.array([10,20,30,40,50])
#Replace values > 30 with 999, else keep original
result = np.where(arr > 30, 999, arr)
print(result)

[ 10  20  30 999 999]


In [35]:
#np.extract() on the basis of where condition it extract elements
arr = np.array([[1,2],[3,4],[5,6]])
condition = arr % 2 == 0

In [36]:
condition

array([[False,  True],
       [False,  True],
       [False,  True]])

In [37]:
result = np.extract(condition, arr)

In [38]:
result

array([2, 4, 6])

In [39]:
#np.nonzero() indices of non zero elements
arr = np.array([[0, 1, 4],
               [2, 2, 3]])
result = np.nonzero(arr)
print(result)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


In [40]:
#np.flatnonzero() Indices of non-zero elements in flattened array
arr = np.array([[0, 1, 0], [2, 0, 3]])

result = np.flatnonzero(arr)
print(result)

[1 3 5]


In [41]:
#np.argwhere() row wise indices of elements where condition is true
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.argwhere(arr > 4)
print(result)

[[1 1]
 [1 2]]


# Exercise

In [42]:
import numpy as np

arr = np.array([[10, 20, 0],
                [0, 50, 60],
                [70, 0, 90]])

In [43]:
# 1. use np.where to replace all zeros with -1
print(np.where(arr == 0, -1, arr))

[[10 20 -1]
 [-1 50 60]
 [70 -1 90]]


In [46]:
# 2. get all values greater than 50
condition = arr>50
result = np.extract(condition, arr)
result

array([60, 70, 90])

In [47]:
# 3. find position of non zero elements
print(np.nonzero(arr))

(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 0, 2], dtype=int64))


In [48]:
# 4. get flat indices of non zero elements
print(np.flatnonzero(arr))

[0 1 4 5 6 8]


In [49]:
# 5. get coordinate of elements which is > 30
print(np.argwhere(arr>30))

[[1 1]
 [1 2]
 [2 0]
 [2 2]]


In [50]:
# 6. extract elements at flat indices [0,4,8]
new_arr = arr.flatten()
flat_indices = np.array([0, 4, 8])

print(new_arr[flat_indices])

[10 50 90]


In [52]:
# 7. select rows where first column is non zero 
condition = arr[:,0] != 0
condition

array([ True, False,  True])

In [56]:
print(np.compress(condition, arr, axis=0))

[[10 20  0]
 [70  0 90]]
